#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ${DISCORD__TOKEN+x} == "" ]]; then
    cat <<-EOF
    ********************************************************
    ********************************************************
    *                                                      *
    *                         !!!!                         *
    *    DISCORD__TOKEN environment variable is not set    *
    *                                                      *
    *                                                      *
    ********************************************************
    ********************************************************
EOF
    sleep infinity
fi

# add option to pass runtime arguments
IFS=" " read -r -a RUN_ARRAY <<<"${JAVA_OPTS}"

cd /app/doplarr/bin || exit

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec \
        s6-setuidgid abc java \
        "${RUN_ARRAY[@]}" \
        -jar /app/doplarr/bin/doplarr.jar
else
    exec \
        java \
        "${RUN_ARRAY[@]}" \
        -jar /app/doplarr/bin/doplarr.jar
fi
