FROM ghcr.io/linuxserver/baseimage-alpine:arm32v7-3.15

# set version label
ARG BUILD_DATE
ARG VERSION
ARG DOPLARR_RELEASE
LABEL build_version="Linuxserver.io version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="nemchik"

# copy local files
COPY root/ /

# This Doplarr image does not support 32 bit ARM due to lack of available OS packages
